sudo: false
language: ruby
rvm:
  - 2.2.1
before_install: gem install bundler -v 1.13
script: rake
deploy:
  provider: rubygems
  api_key:
    secure: "NH5KmUEJybHQCUI+QRpeh5RsPooI9rSs++jpSYCkyhggUO2q+J/zakMlc8KGnU+ZYFGxkv2DSJhuBKXqi8r0QRntiKfwLWQMX+p8h52ujaXVYisLjVJ0yZPkNiY71rBEcA0qgXk2yjwX8wDnGPDioYA6yvrolQmeXf1HCo1tnDgnSSqzxkC86ExZADCntOxKWwiqBoiHRxYBNCQIgoddl813z6taV8zsddNgT3SqvEFHw4i+MKnZz/CS0UEN20lBT+TvGdDsi8ncrFaAFxtGr3cHSkFCD/gWunikYO6mEoOnne+RkMmN9TBZlD0XD0Q94xZCXpE7qpDB2DxM2ogMvEI2P22Mck5O+ILeuVXFe86RUYTxx+t73qD+hqBjEIC7U3IXkTeexEYQm9YJ+gpa9CqhJVblyTlChzm6CWKlQc7jtjIjXpAoOuD0qg5fpnzTv+ez+tWQjPv3F/JBQ2T6jErC6m9ycpE8nbgYhHRXGwb4pzps8MfW8LUyXTIcyuNAidVhloAzu9DK0qqBX3NzK2S8xbZMVd6KtFumuy3I2lVGzBaIgFOvGQbfLVTrkYZ4xcyd3XgBTDk3Dl1czc336BlY8hkAzxXXep6agbGmLW9tIASlh/Sab+TPIB6BR7yGYo8VdIqbh5Bl9EBxrDCXqp8nczMtEb9L7B2UlKhfb4E="
  gem: elastip
  on:
    tags: true
    repo: pcboy/elastip
