#!/usr/bin/env ruby

require 'elastip'

project, env, *options = ARGV
options ||= []
if !project or !env
  abort "Usage: elastip <project name regexp> <environnement (e.g staging production)> [--all] [--inactive] [--terminate]\n" \
        "Example: elastip 'my_pro*ect' production"
end

if options.include?('--inactive')
  puts Elastip::Elastip.new(project, env, all: options.include?('--all')).inactive_instances(terminate: options.include?('--terminate')).join("\n")
else
  puts Elastip::Elastip.new(project, env, all: options.include?('--all')).ip.join("\n")
end
