#!/usr/bin/env ruby

require 'elastip'

project, env, options = ARGV
options ||= []
if !project or !env
  abort "Usage: elastip <project name regexp> <environnement (e.g staging production)> [--all]\n" \
        "Example: elastip 'my_pro*ect' production"
end

puts Elastip::Elastip.new(project, env, options).ip.join("\n")
